services:

  api:
    image: api
    build:
      context: api/   # Ubicacion del dockerfile
    container_name: api  # Nombre del contenedor
    hostname: api  # Nombre de host dentro de la red de Docker
    networks:
      - my_chat  # Conecta los contenedores a la misma red
    environment:
      - MONGO_URI
      - SECRET_KEY
      - ALGORITHM
    ports:
      - "8000:8000"  # Expone el puerto 8000 externamente
    restart: always  # Reinicia siempre si falla
    profiles:
      - full  # Perfil de ejecución específico
      - back

  front:
    image: front
    build: 
      context: front/
    container_name: front
    hostname: front
    networks:
      - my_chat
    environment:
      - TZ
    ports:
      - '5173:5173'
    restart: always
    depends_on:
      - api
    profiles:
      - full
      - front

networks:
  my_chat:
    name: my_chat  # Define una red
    driver: bridge
    